### ISSUE TITLE
ubuntu-cloud-image page has copypasted line from ubuntu-bug-triage

### ISSUE THREAD

**Issue by paride** [powersj/powersj.github.io#1]
Hi :) https://powersj.io/projects/ubuntu-cloud-image/ has this line:

> For example, to find bugs updated in the last 30 days for the libvirt package a user would run:

you likely forgot to amend while using the ubuntu-bug-triage page as a template.

**Comment by powersj** [comment]
Thanks for the catch :) and yes, you caught my copy and paste error. Fixed.
